### ISSUE TITLE
Program doesn't see SecurityCraft for 1.12

### ISSUE THREAD

**Issue by Maximka310** [Procybit/Ky3M#1]
![1012f3dc02130dba63d518fc52255b77](https://user-images.githubusercontent.com/86533658/183471222-b08e6fba-f46f-48fa-96e3-9d3c2005a1ca.png)
[1.12.xSecurityCraftv1.8.8.zip](https://github.com/Procybit/Ky3M/files/9283624/1.12.xSecurityCraftv1.8.8.zip)

**Comment by Procybit** [comment]
I've fixed issue you've found.
Fix will be included in 0.1.1 release.
Tnank you for feedback.
