### ISSUE TITLE
[FEATURE] Add "help" command.

### ISSUE THREAD

**Issue by Maximka310** [Procybit/Ky3M#9]
It is inconvenient to open the browser every time when you want to remember how this or that method is written or used. I hope in the next updates you will add the help command.

**Comment by Procybit** [comment]
Allowable. Then what sort of information would you like to see when you call the help command?

**Comment by Procybit** [comment]
I've published [dev-release](https://github.com/Procybit/Ky3M/releases/v0.2.3.dev1) that includes "help command" test-feature. What do you think?

**Comment by Maximka310** [comment]
I like it.
